/** Canonical fields grouped for the mapping dropdowns (mirrors the dictionary). */
export const FIELD_OPTIONS: Array<{ value: string; label: string; group: string }> = [
  { value: "email", label: "Email", group: "Contact" },
  { value: "phone", label: "Phone", group: "Contact" },
  { value: "websiteUrl", label: "Website", group: "Contact" },
  { value: "twitterUrl", label: "X / Twitter", group: "Contact" },
  { value: "instagramUrl", label: "Instagram", group: "Contact" },
  { value: "facebookUrl", label: "Facebook", group: "Contact" },
  { value: "linkedinUrl", label: "LinkedIn", group: "Contact" },
  { value: "tiktokUrl", label: "TikTok", group: "Contact" },
  { value: "goodreadsUrl", label: "Goodreads", group: "Contact" },
  { value: "fullName", label: "Full name", group: "Person" },
  { value: "authorName", label: "Author name", group: "Person" },
  { value: "firstName", label: "First name", group: "Person" },
  { value: "lastName", label: "Last name", group: "Person" },
  { value: "organization", label: "Organization", group: "Person" },
  { value: "role", label: "Role / title", group: "Person" },
  { value: "notes", label: "Notes", group: "Person" },
  { value: "bookTitle", label: "Book title", group: "Book" },
  { value: "subtitle", label: "Subtitle", group: "Book" },
  { value: "seriesName", label: "Series", group: "Book" },
  { value: "seriesPosition", label: "Series number", group: "Book" },
  { value: "genre", label: "Genre", group: "Book" },
  { value: "description", label: "Description", group: "Book" },
  { value: "bookUrl", label: "Book URL", group: "Book" },
  { value: "amazonUrl", label: "Amazon URL", group: "Book" },
  { value: "isbn", label: "ISBN", group: "Book" },
  { value: "publisher", label: "Publisher", group: "Book" },
  { value: "publicationDate", label: "Publication date", group: "Book" },
  { value: "bookFormat", label: "Format", group: "Book" },
  { value: "language", label: "Language", group: "Book" },
];
